version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - "8000:8000"
      - "5678:5678"  # Expose debugpy port
    volumes:
      - .:/app
    command: >
      sh -c "pipenv run python -m debugpy --wait-for-client --listen 0.0.0.0:5678
             manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1
    # ... other configurations ...