# Generated by Django 5.1 on 2024-08-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
    ]
