---
- name: Deploy Django application with Nginx
  hosts: django_server
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Docker dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Copy SSH key to a specific location (if needed)
      copy:
        src: "{{ ansible_ssh_private_key_file }}"
        dest: "/home/{{ ansible_user }}/.ssh/private_key.pem"
        mode: '0600'
      when: ansible_ssh_private_key_file is defined

    - name: Create a directory for the Django app
      file:
        path: /opt/django_app
        state: directory
        mode: '0755'

    - name: Copy Django project files to the server
      synchronize:
        src: "{{ playbook_dir }}/.."
        dest: /opt/django_app
        delete: yes
        use_ssh_args: yes
        rsync_opts:
          - "--exclude=*.pyc"
          - "--exclude=__pycache__"
          - "--exclude=.venv"
          - "--exclude=.git"

    - name: Build Docker image
      docker_image:
        name: django_app
        build:
          path: /opt/django_app
        source: build
        force_source: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"

    - name: Remove default Nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Create Nginx configuration for Django app
      template:
        src: templates/nginx_django.conf.j2
        dest: /etc/nginx/sites-available/django_app
      notify: Reload Nginx

    - name: Enable Nginx site for Django app
      file:
        src: /etc/nginx/sites-available/django_app
        dest: /etc/nginx/sites-enabled/django_app
        state: link
      notify: Reload Nginx

    - name: Run Django Docker container
      docker_container:
        name: django_app
        image: django_app:latest
        state: started
        restart_policy: always
        published_ports:
          - "8000:8000"

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded