name: Deploy Django to AWS EC2

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init and Apply
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve

      - name: Debug Terraform Outputs
        run: |
          cd terraform
          echo "\nRaw public_ip output:"
          terraform-bin output -raw public_ip
          echo "\nRaw key_name output:"
          terraform-bin output -raw key_name

      - name: Get Terraform Outputs
        id: outputs
        run: |
          cd terraform
          PUBLIC_IP=$(terraform-bin output -raw public_ip)
          echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV
          KEY_NAME=$(terraform-bin output -raw key_name)
          echo "KEY_NAME=$KEY_NAME" >> $GITHUB_ENV

      - name: Use Terraform Output in GitHub Actions
        run: |
          echo "The instance IP is ${{ env.PUBLIC_IP }}"
          echo "The key name is ${{ env.KEY_NAME }}"

      - name: Setup Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Update Ansible inventory
        run: |
          echo "all:
            hosts:
              django_server:
                ansible_host: ${{ env.PUBLIC_IP }}
                ansible_user: ubuntu
                ansible_ssh_private_key_file: ./terraform/${{ env.KEY_NAME }}.pem" > ansible/inventory.yml

      - name: Run Ansible playbook
        run: |
          ansible-inventory -i ansible/inventory.yml --list
          chmod 600 terraform/${{ env.KEY_NAME }}.pem
          ansible-playbook -i ansible/inventory.yml ansible/playbook.yml