name: Deploy Django to AWS EC2

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init and Apply
        id: terraform
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve
          # echo "KEY_NAME=$(terraform output -raw key_name)" >> $GITHUB_ENV

      - name: Get Terraform Outputs
        id: outputs
        run: |
          echo "PUBLIC_IP=$(terraform output -raw public_ip)" >> $GITHUB_ENV

      - name: Use Terraform Output in GitHub Actions
        run: echo "The instance IP is ${{ env.PUBLIC_IP }}"

      - name: Setup Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Update Ansible inventory
        run: |
          echo "all:
            hosts:
              django_server:
                ansible_host: ${{ env.PUBLIC_IP }}
                ansible_user: ec2-user
                ansible_ssh_private_key_file: ./terraform/${{ env.KEY_NAME }}.pem" > ansible/inventory.yml

      - name: Run Ansible playbook
        run: |
          chmod 600 terraform/${{ env.KEY_NAME }}.pem
          ansible-playbook -i ansible/inventory.yml ansible/playbook.yml